import { RoomWithDetails } from "@/src/types/room";

/**
 * Skeleton rooms used for loading states
 * Clean rooms with no reservations or notes - just structure
 */
export const skeletonRooms: RoomWithDetails[] = [
  {
    id: "skeleton-room-1",
    name: "Loading room...",
    description: "Please wait while we load your rooms",
    floor: 1,
    capacity: 12,
    type: "workspace",
    wheelchair_accessible: false,
    has_elevator: false,
    pet_friendly: false,
    published: true,
    company_id: null,
    deleted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    seats: Array.from({ length: 12 }, (_, i) => ({
      id: `skeleton-seat-1-${i + 1}`,
      room_id: "skeleton-room-1",
      number: i + 1,
      status: "available" as const,
      amenities: [],
      note: null,
      deleted_at: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      reservations: [],
    })),
  },
  {
    id: "skeleton-room-2",
    name: "Loading room...",
    description: "Please wait while we load your rooms",
    floor: 2,
    capacity: 12,
    type: "workspace",
    wheelchair_accessible: false,
    has_elevator: false,
    pet_friendly: false,
    published: true,
    company_id: null,
    deleted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    seats: Array.from({ length: 12 }, (_, i) => ({
      id: `skeleton-seat-2-${i + 1}`,
      room_id: "skeleton-room-2",
      number: i + 1,
      status: "available" as const,
      amenities: [],
      note: null,
      deleted_at: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      reservations: [],
    })),
  },
  {
    id: "skeleton-room-3",
    name: "Loading room...",
    description: "Please wait while we load your rooms",
    floor: 1,
    capacity: 12,
    type: "workspace",
    wheelchair_accessible: false,
    has_elevator: false,
    pet_friendly: false,
    published: true,
    company_id: null,
    deleted_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    seats: Array.from({ length: 12 }, (_, i) => ({
      id: `skeleton-seat-3-${i + 1}`,
      room_id: "skeleton-room-3",
      number: i + 1,
      status: "available" as const,
      amenities: [],
      note: null,
      deleted_at: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      reservations: [],
    })),
  },
];
